name: CI

on:
  push:
    branches: [master, dev, workflow, cmake, fix, hotfix]
  pull_request:
    branches: [master, dev, workflow, cmake, fix, hotfix]

jobs:
  ubuntu-asan:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get install flex graphviz
        wget http://ftp.gnu.org/gnu/bison/bison-3.5.tar.gz
        tar -zxvf bison-3.5.tar.gz
        cd bison-3.5/
        sudo ./configure
        sudo make
        sudo make install
        sudo ln -s /usr/local/bin/bison /usr/bin/bison
        cd ..

    - name: Configure asan build
      run: cmake . -B asan_build -DCMAKE_BUILD_TYPE=ASAN

    - name: Build with address sanitizer
      run: cmake --build asan_build -j 2 -t compiler-mini-java

    - name: Run tests
      run: |
        cd asan_build/samples
        ctest

  macos-asan:
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: brew install flex bison graphviz

    - name: Configure asan build
      run: cmake . -B asan_build -DCMAKE_BUILD_TYPE=ASAN

    - name: Build with address sanitizer
      run: cmake --build asan_build -j 2 -t compiler-mini-java

    - name: Run tests
      run: |
        cd asan_build/samples
        ctest
